### PR TITLE
Add event theme template

### PR DESCRIPTION
**Pull request by patcon**
Look decent enough? (see review app link below)

I'll start doing customization in other PRs

cc: @ebarry @DZNarayanan @misscs

### CODE REVIEW

**Comment by misscs** [comment]
@patcon Looks great! I'm DTM 🎉

**Comment by ebarry** [comment]
the theme looks great -- but is that Kuala Lumpur???

**Comment by DZNarayanan** [comment]
Yeah. The framework is great!! I'm guessing the pic and video are a
placeholders?

**Comment by misscs** [comment]
@patcon said he would be updating the content in another PR :)

**Comment by DZNarayanan** [comment]
Ah. I see it now!

**Comment by patcon** [comment]
:raised_hands:

**Pull request merged**
